name: SISCONT_Mobile
description: Aplicativo SISCONT Mobile com Supabase
version: 1.0.0+3

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.9.1
  sign_in_with_apple: ^7.0.1
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  flutter_image_compress: ^2.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3
  shared_preferences: ^2.2.0
  http: ^1.1.0
  share_plus: ^11.0.0
  pdf: ^3.10.7
  printing: ^5.9.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  url_launcher: ^6.3.1
  device_info_plus: ^11.5.0
  uuid: ^4.5.1

flutter:
    uses-material-design: true
    assets:
      - imagens/SISCONT_LOGO.png    

dev_dependencies:
  change_app_package_name: ^1.1.0
